FROM baseimage

RUN command

COPY source dest

WORKDIR /app

EXPOSE 8080

ENV key=value

CMD [ "executable" ]        or CMD ["command", "parameter 1", "parameter 2", ....]  or CMD command parameter1 parameter2 ...


# Set noninteractive mode
ENV DEBIAN_FRONTEND=noninteractive